<section class="industris-v4">
                
                <div class="container-fluid">
                    <div class="ot-industries">
                        <div class="owl-carousel owl-theme industries-inner ot-industries-slider">

                            <div class="indus-item">
                                <div class="item-inner">
                                    <div class="overlay"></div>
                                    <div class="i-image">
                                        <img src="https://via.placeholder.com/139x141.png" alt="">
                                    </div>
                                    <div class="iinfo">
                                        <h6>International</h6>
                                        <div class="itext">
                                            The global economy is moving towards a new identity. In order to remain competitive and profitable, the banking and finance.
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="indus-item">
                                <div class="item-inner">
                                    <div class="overlay"></div>
                                    <div class="i-image">
                                        <img src="https://via.placeholder.com/139x141.png" alt="">
                                    </div>
                                    <div class="iinfo">
                                        <h6>Education</h6>
                                        <div class="itext">
                                            The global economy is moving towards a new identity. In order to remain competitive and profitable, the banking and finance.
                                        </div>
                                    </div>
                                </div>
                            </div>

          
                            <div class="indus-item">
                                <div class="item-inner">
                                    <div class="overlay"></div>
                                    <div class="i-image">
                                        <img src="https://via.placeholder.com/139x141.png" alt="">
                                    </div>
                                    <div class="iinfo">
                                        <h6>Window</h6>
                                        <div class="itext">
                                            The global economy is moving towards a new identity. In order to remain competitive and profitable, the banking and finance.
                                        </div>
                                    </div>
                                </div>
                            </div>
 
                        </div>
                    </div>
                </div>
            </section>