
        <!--== Start Slider Area Wrapper ==-->
        <div class="slider-area slider-area--multipurpose">
            <div class="slider-activation">
                <div class="slider-item bg-img" data-bg="<?= $this->basePath().'/assets/' ?>img/sliders/slider-multipurpose-1.jpg">
                    <div class="container">
                        <div class="row align-items-center no-gutters">
                            <div class="col-lg-5 order-1 order-lg-0 text-center text-lg-right">
                                <div class="slider-content slider-content--multipurpose slide-1">
                                    <h2>ITIS-DE Agency</h2>
                                    <p>IT Innovative Skills & Data Engineering</p>
                                    <a href="#" class="btn btn-brand">More Info</a>
                                </div>
                            </div>

                            <div class="col-lg-7 text-lg-right order-0 order-lg-1">
                                <div class="slider-thumb slider-thumb--multipurpose popup-video">
                                    <img src="<?= $this->basePath().'/assets/' ?>img/sliders/slider-multipurpose-1.1.jpg" alt="Slider" />

                                    <a href="https://www.youtube.com/watch?v=jwiIzNIK4dg" class="btn-video-popup">
                                        <img src="assets/img/icons/play.png" alt="Video">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="slider-item bg-img" data-bg="<?= $this->basePath().'/assets/' ?>img/sliders/slider-multipurpose-2.jpg">
                    <div class="container">
                        <div class="row align-items-center no-gutters">
                            <div class="col-12 text-center">
                                <div class="slider-content slider-content--multipurpose slide-2">
                                    <h2>Nos Expertises</h2>
                                    <p>Offrir une expérience digitale unique et efficace à vos clients grâce à une stratégie webmarketing adaptée à vos objectifs, aux tendances du web et aux habitudes des internautes.</p>
                                    <a href="#" class="btn btn-brand">More Info</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="slider-item bg-img" data-bg="<?= $this->basePath().'/assets/' ?>img/sliders/slider-multipurpose-3.jpg">
                    <div class="container-fluid">
                        <div class="row align-items-center no-gutters">
                            <div class="col-12 text-center text-lg-left">
                                <div class="slider-content slider-content--multipurpose slide-3">
                                    <h2>Nos Services</h2>
                                    <p>Nous concevons et construisons des modèles d'apprentissage automatique, ingénierie de données et développement des projets numériques.</p>
                                    <a href="#" class="btn btn-hvr-brand">More Info</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--== End Slider Area Wrapper ==-->