
<section class="home2-top">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-6 text-center text-lg-left mb-4 mb-lg-0">
                            <img src="<?= $this->basePath(); ?>/assets/images/iew_slide_two.png" alt="IEW">
                        </div>
                        <div class="col-lg-6 align-self-center">
                            <div class="home2-top-right">
                                <p class="small-text">// IEW - Études à l'étranger</p>
                                <h2>INTERNATIONAL EDUCATION WINDOW</h2>
                                <p class="sub-text text-small">IEW est une agence spécialisée dans le conseil et l’orientation des élèves 
                                et étudiants et leur recrutement dans les établissements de l’enseignement supérieur au Maroc et à l’étranger.</p>
                                <div class="video-popup style-2">
                                    <div class="btn-inner">
                                        <a class="btn-play" href="https://vimeo.com/94686522"><i class="flaticon-play"></i>
                                            <span class="circle-1"></span>
                                            <span class="circle-2"></span>
                                        </a>
                                    </div>
                                    <span>video showcase</span>     
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
</section>