<?php echo $this->partial("partials/header.phtml", 
                            ['categories' => $categories ,
                            'subcats' => $subcats ,
                            'contact' => $contact,
                            'form' => $form,
                            'candidatForm' => $candidatForm]); ?>

 

    
        <?php echo $this->partial("partials/slides.phtml", ['postsRevolution' => $postsRevolution]); ?>




         <!--== Start About Area Wrapper ==-->
         <section class="about-area sm-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-6 col-lg-4 order-lg-1">
                        <div class="section-title section-title--3 quote-title">
                            <h3>Motivated by the desire <strong>to achieve.</strong></h3>
                        </div>
                    </div>

                    <div class="col-lg-8 order-lg-0">
                        <div class="about-feature-wrap about-feature--creative-agency">
                            <div class="row mtn-100 mtn-sm-30 mtn-md-50">
                                <div class="col-md-6">
                                    <div class="icon-box icon-box--mini">
                                        <div class="icon-box-icon">
                                            <i class="icon-basic-signs"></i>
                                        </div>

                                        <div class="icon-box-info">
                                            <h4>Développement Web/Mobile</h4>
                                            <p>Développement des applications web et mobile sur mesure.</p>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="icon-box icon-box--mini">
                                        <div class="icon-box-icon">
                                            <i class="icon-basic-display"></i>
                                        </div>

                                        <div class="icon-box-info">
                                            <h4>UI/UX Web Design</h4>
                                            <p>Nous fournissons à l'utilisateur une interface accessible et intuitive</p>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="icon-box icon-box--mini">
                                        <div class="icon-box-icon">
                                            <i class="icon-basic-lightbulb"></i>
                                        </div>

                                        <div class="icon-box-info">
                                            <h4>Ingénierie de données et L'intélligence artificielle</h4>
                                            <p>Nous pouvons réaliser une architecture de données à partir de zéro ou développer des fonctionnalités supplémentaires</p>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="icon-box icon-box--mini">
                                        <div class="icon-box-icon">
                                            <i class="icon-basic-magnifier"></i>
                                        </div>

                                        <div class="icon-box-info">
                                            <h4>SEO Référencement naturel</h4>
                                            <p>Le référencement SEO naturel offre une présence de recherche visible et efficace.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--== End About Area Wrapper ==-->


        <!--== Start Call to Action Area ==-->
        <div class="call-to-action call-to-action--startup sm-top-lh">
            <div class="row">
                <div class="col-md-7 col-lg-6 order-1 order-md-0">
                    <div class="call-to-action-content marketing-agency bg-blackSoft">
                        <div class="call-to-action-content-inner">
                            <h2>Hit the target</h2>
                            <p>Your website will be your calling card, and you cannot afford to present a sub-standard
                                design.</p>
                            <a href="portfolio.html" class="btn btn-brand">View Demo</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-5 col-lg-6 order-0 order-md-1">
                    <div class="call-to-action-thumb popup-video bg-img" data-bg="<?= $this->basePath().'/assets/' ?>img/action.jpg">
                        <a href="https://www.youtube.com/watch?v=jwiIzNIK4dg" class="btn-video-popup"><img src="assets/img/icons/play.png" alt="Video"></a>
                    </div>
                </div>
            </div>
        </div>
        <!--== End Call to Action Area ==-->

  <!--== Start Call to Action Area ==-->
  <div class="call-to-action bg-img" data-bg="assets/img/call-to-action/marketing-agency-2.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="call-to-action-content call-to-action-content--black">
                            <div class="call-left-text">
                                <h3>Démarrer un nouveau projet ?</h3>
                                <p>ITISDE agency est votre choix ultime.</p>
                            </div>
                            <a href="contact.html" class="btn btn-brand">Contactez-nous</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--== End Call to Action Area ==-->
       

        <!--== Start Skills Area Wrapper ==-->
        <div class="skills-area">
            <div class="row no-gutters">
                <div class="col-lg-6">
                    <div class="skills-left-wrapper sp-y bg-img" data-bg="<?= $this->basePath().'/assets/' ?>img/marketing-agency.jpg">
                        <div class="row">
                            <div class="col-xl-8 ml-auto">
                                <div class="skills-heading-wrap skills-heading-wrap--2">
                                    <h3>Stratégie de marque et création digitale.</h3>
                                    <p class="text">ITISDE fournit la solution ultime pour réaliser votre futur projet numérique Avec des outils et des éléments inimaginables, ITISDE a tout pour tout le monde.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 align-self-stretch">
                    <div class="skills-right-wrapper bg-whitesoft h-100">
                        <div class="row align-items-center h-100">
                            <div class="col-xl-6 offset-lg-1">
                                <div class="skills-progressbar-wrap pl-xl-5 mtn-30">
                                    <!--= Start Progressbar Item =-->
                                    <div class="progressbar-item progressbar-item--line">
                                        <div class="progress-info">
                                            <span class="progress-info__title">Développement Web/Mobile</span>
                                            <span class="progress-info__percent percent"></span>
                                        </div>

                                        <div class="progress-line">
                                            <div class="progress-line-bar" data-percent="98%"></div>
                                        </div>
                                    </div>
                                    <!--= End Progressbar Item =-->

                                    <!--= Start Progressbar Item =-->
                                    <div class="progressbar-item progressbar-item--line">
                                        <div class="progress-info">
                                            <span class="progress-info__title">Ingénierie de données et L'intélligence artificielle</span>
                                            <span class="progress-info__percent percent"></span>
                                        </div>

                                        <div class="progress-line">
                                            <div class="progress-line-bar" data-percent="95%"></div>
                                        </div>
                                    </div>
                                    <!--= End Progressbar Item =-->

                                    <!--= Start Progressbar Item =-->
                                    <div class="progressbar-item progressbar-item--line">
                                        <div class="progress-info">
                                            <span class="progress-info__title">UI/UX</span>
                                            <span class="progress-info__percent percent"></span>
                                        </div>

                                        <div class="progress-line">
                                            <div class="progress-line-bar" data-percent="85%"></div>
                                        </div>
                                    </div>
                                    <!--= End Progressbar Item =-->

                                    <!--= Start Progressbar Item =-->
                                    <div class="progressbar-item progressbar-item--line">
                                        <div class="progress-info">
                                            <span class="progress-info__title">SEO Référencement naturel</span>
                                            <span class="progress-info__percent percent"></span>
                                        </div>

                                        <div class="progress-line">
                                            <div class="progress-line-bar" data-percent="80%"></div>
                                        </div>
                                    </div>
                                    <!--= End Progressbar Item =-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--== End Skills Area Wrapper ==-->
 


      

        <!--== Start Testimonial Area ==-->
        <div class="testimonial-area  sp-y bg-img" data-bg="<?= $this->basePath().'/assets/' ?>img/multipurpose.jpg">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 m-auto">
                        <div class="testimonial-multipurpose-wrap">
                            <div class="multipurpose-testimonial-slider text-center slick-dots-round">
                                <!--= Start Testimonial Item =-->
                                <div class="testimonial-item">
                                    <div class="testimonial-item-author">
                                        <h4 class="name">Zahr-eddine</h4>
                                        <span class="tagline">ITISDE, IT Developer & Technical Machine Learning</span>
                                    </div>

                                    <div class="testimonial-item-quote">
                                        <p>“Success is no accident. It is hard work, perseverance, learning, studying,
                                            sacrifice
                                            and most of all, love of what you are doing or learning to do.”</p>
                                    </div>
                                </div>
                                <!--= End Testimonial Item =-->

                                <!--= Start Testimonial Item =
                                <div class="testimonial-item">
                                    <div class="testimonial-item-author">
                                        <h4 class="name">Blanche Fields</h4>
                                        <span class="tagline">Banana, CEO</span>
                                    </div>

                                    <div class="testimonial-item-quote">
                                        <p>“Success is no accident. It is hard work, perseverance, learning, studying,
                                            sacrifice
                                            and most of all, love of what you are doing or learning to do.”</p>
                                    </div>
                                </div>-->
                                <!--= End Testimonial Item =-->

                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--== End Testimonial Area ==-->


        <?php //echo $this->partial("partials/sec_iew.phtml"); ?>

        <?php //echo $this->partial("partials/video_demo.phtml"); ?>

        <?php //echo $this->partial("partials/last_articles.phtml", ['postsArticles' => $postsArticles]); ?>

        <?php //echo $this->partial("partials/last_news.phtml", ['postsAnnonces' => $postsAnnonces]); ?>

        <?php //echo $this->partial("partials/last_blog.phtml", ['postsBlogs' => $postsBlogs]); ?>

 <!--== Start Map Area ==-->
 <div class="map-onepage map">
 <div class="map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13242.645503545264!2d-6.9313777!3d33.9241138!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x306d60524a06d703!2sInternational%20Education%20Window!5e0!3m2!1sen!2sma!4v1615080452007!5m2!1sen!2sma" height="540" width="100%"  style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                </div>
        </div>
        <!--== End Map Area ==-->
   
 
        <?php echo $this->partial("partials/footer.phtml" , ['categories' => $categories ,
                            'subcats' => $subcats ,'contact' => $contact]); ?>



 
 
 